### ISSUE TITLE
RFR: nodejs-dropbox-clone

### ISSUE THREAD

**Issue by yidea** [yidea/nodejs-dropbox-clone#1]
Ping for review /cc @codepathreview @codepath

PS. Have some question about what's the best practice for express error handling and what to return to response, the code I have is not quite consistent, I'm not sure if there's a better way to do it. Aslo want to have a better understanding on process.nexttick use case vs. setTimout(0) in nodejs. Thanks!

**Comment by codepathreview** [comment]
:+1: nice work. The point of this homework was to explore a simple example of a full server application with a REST API and CLI while interacting with the filesystem. 
Here's a checklist of things that I'm looking for in this project. You should review the checklist, and make any changes to your project, if necessary.
- Airbnb has a good summary of appropriate JavaScript coding conventions, you should take a quick look [here](https://github.com/airbnb/javascript).
- You should always try to minimize the number of installed and required dependencies. Modularize your code as much as possible, and avoid globals.
- Declaring REST routes as separate functions will make your code more extensible and supportable.
- You should always ensure you're sending the **most correct** HTTP status codes and all relevant headers. In SOA, the difference between a 500 and a 502 is the difference between an error in your code and an error in a downstream service, which can save hours of debugging. Take a moment to review the list of [HTTP status codes](http://en.wikipedia.org/wiki/List_of_HTTP_status_codes) and [HTTP headers](http://en.wikipedia.org/wiki/List_of_HTTP_header_fields).
- When consuming TCP APIs, packets should be checked for split messages and buffered to reconstruct the JSON payload.
- You should always take extra precautions like this when interacting with the filesystem to avoid catastrophic mistakes like removing `/`.
- Sync APIs should never be used in production code except during the brief startup phase of a server's lifecycle. Use the [safeguards package](https://github.com/CrabDude/safeguards) to protect against this.

In general, you should challenge yourself to create fast stable applications with strict APIs. That's where you'll find all the rough edges of the node.js runtime and earn the next level of mastery.
